// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260506203659_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Barber", b =>
                {
                    b.Property<Guid>("barberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("salonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("barberId");

                    b.HasIndex("salonId");

                    b.ToTable("Barbers");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<Guid>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("customerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("timeslotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("bookingId");

                    b.HasIndex("timeslotId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("backend.Models.Salon", b =>
                {
                    b.Property<Guid>("salonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("salonId");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("backend.Models.Timeslot", b =>
                {
                    b.Property<Guid>("timeslotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("barberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<Guid?>("salonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("startTime")
                        .HasColumnType("time");

                    b.HasKey("timeslotId");

                    b.HasIndex("barberId");

                    b.HasIndex("salonId");

                    b.ToTable("Timeslots");
                });

            modelBuilder.Entity("backend.Models.Barber", b =>
                {
                    b.HasOne("backend.Models.Salon", null)
                        .WithMany("barbers")
                        .HasForeignKey("salonId");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.Timeslot", "timeslot")
                        .WithMany()
                        .HasForeignKey("timeslotId");

                    b.Navigation("timeslot");
                });

            modelBuilder.Entity("backend.Models.Timeslot", b =>
                {
                    b.HasOne("backend.Models.Barber", "barber")
                        .WithMany()
                        .HasForeignKey("barberId");

                    b.HasOne("backend.Models.Salon", "salon")
                        .WithMany()
                        .HasForeignKey("salonId");

                    b.Navigation("barber");

                    b.Navigation("salon");
                });

            modelBuilder.Entity("backend.Models.Salon", b =>
                {
                    b.Navigation("barbers");
                });
#pragma warning restore 612, 618
        }
    }
}
